export const ProductCategoryData = [
    { name: "Beauty", y: 4 },
    { name: "Fragrances", y: 4 },
    { name: "Furniture", y: 4 },
    { name: "Groceries", y: 4 },
    { name: "Home Decoration", y: 4 },
    { name: "Kitchen Accessories", y: 4 },
    { name: "Laptops", y: 4 },
    { name: "Mens Shirts", y: 4 },
    { name: "Mens Shoes", y: 4 },
    { name: "Mens Watches", y: 4 },
    { name: "Mobile Accessories", y: 4 },
    { name: "Motorcycle", y: 4 },
    { name: "Skin Care", y: 4 },
    { name: "Smartphones", y: 4 },
    { name: "Sports Accessories", y: 4 },
    { name: "Sunglasses", y: 4 },
    { name: "Tablets", y: 4 },
    { name: "Tops", y: 4 },
    { name: "Vehicle", y: 4 },
    { name: "Womens Bags", y: 4 },
    { name: "Womens Dresses", y: 4 },
    { name: "Womens Jewellery", y: 4 },
    { name: "Womens Shoes", y: 4 },
    { name: "Womens Watches", y: 4 }
];